# Generated by Django 3.2.3 on 2021-06-09 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crate_sizing', '0002_auto_20210608_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='cust_info',
            name='zip',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
