# Generated by Django 3.2.3 on 2021-06-09 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crate_sizing', '0003_cust_info_zip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ship_via',
        ),
        migrations.AddField(
            model_name='cust_info',
            name='ship_via',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
