# Generated by Django 3.2.3 on 2021-06-12 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crate_sizing', '0004_auto_20210608_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_specs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_numbs', models.CharField(max_length=200)),
                ('max_height', models.CharField(max_length=200)),
                ('total_sqft', models.CharField(max_length=200)),
            ],
        ),
    ]
