# Generated by Django 3.2.3 on 2021-06-17 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crate_sizing', '0005_order_specs'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_specs',
            name='corner_brace_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order_specs',
            name='corner_brace_width',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order_specs',
            name='crate_bottom_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order_specs',
            name='crate_bottom_width',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order_specs',
            name='crate_ends_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order_specs',
            name='crate_ends_width',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order_specs',
            name='crate_height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order_specs',
            name='crate_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order_specs',
            name='crate_sides_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order_specs',
            name='crate_sides_width',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order_specs',
            name='crate_top_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order_specs',
            name='crate_top_width',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order_specs',
            name='crate_width',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order_specs',
            name='height_list',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order_specs',
            name='job_numbers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order_specs',
            name='sqft_list',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order_specs',
            name='total_height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order_specs',
            name='total_width',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order_specs',
            name='job_numbs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order_specs',
            name='max_height',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order_specs',
            name='total_sqft',
            field=models.IntegerField(default=0),
        ),
    ]
