# Generated by Django 3.2.3 on 2021-06-18 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crate_sizing', '0007_auto_20210616_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_number', models.IntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crate_sizing.order')),
            ],
        ),
    ]
