# Generated by Django 3.2.3 on 2021-06-19 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crate_sizing', '0009_auto_20210618_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='corner_brace_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='corner_brace_width',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='crate_bottom_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='crate_bottom_width',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='crate_ends_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='crate_ends_width',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='crate_height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='crate_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='crate_sides_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='crate_sides_width',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='crate_top_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='crate_top_width',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='crate_width',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='sq_ft',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Job_number',
        ),
        migrations.AddField(
            model_name='job',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crate_sizing.order'),
        ),
    ]
