# Generated by Django 3.2.3 on 2021-06-24 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crate_sizing', '0012_alter_order_job_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='job_number',
        ),
    ]
