# Generated by Django 3.2.3 on 2021-06-24 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crate_sizing', '0013_remove_order_job_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Job',
            new_name='Job_numbers',
        ),
    ]
