# Generated by Django 3.2.3 on 2021-06-24 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crate_sizing', '0014_rename_job_job_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_numbers',
            name='job_number',
            field=models.CharField(max_length=200),
        ),
    ]
