# Generated by Django 3.2.3 on 2021-06-24 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crate_sizing', '0015_alter_job_numbers_job_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_numbers',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='crate_sizing.order'),
        ),
    ]
