# Generated by Django 3.2.3 on 2021-06-26 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crate_sizing', '0018_order_total_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='max_height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='sqft',
            field=models.IntegerField(default=0),
        ),
    ]
