# Generated by Django 3.2.3 on 2021-06-30 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crate_sizing', '0021_remove_order_sq_ft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='crate_top_length',
            field=models.FloatField(default=0),
        ),
    ]
