# Generated by Django 3.2.3 on 2021-06-30 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crate_sizing', '0022_alter_order_crate_top_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='corner_brace_length',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='corner_brace_width',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='crate_bottom_length',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='crate_bottom_width',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='crate_ends_length',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='crate_ends_width',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='crate_sides_length',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='crate_sides_width',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='crate_top_width',
            field=models.FloatField(default=0),
        ),
    ]
