# Generated by Django 3.2.3 on 2021-06-30 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crate_sizing', '0023_auto_20210629_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='crate_height',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='crate_length',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='crate_width',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='max_height',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='sqft',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_height',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_width',
            field=models.FloatField(default=0),
        ),
    ]
