# Generated by Django 3.2.3 on 2021-07-01 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crate_sizing', '0024_auto_20210629_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_height',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_width',
        ),
    ]
